alias gz="cd ~/.config/zsh"
alias gc="cd ~/.config"
alias gn="cd ~/.config/nvim"
alias gi="cd ~/.config/i3"
alias gd="cd ~/Desktop"
alias gw="cd ~/wallpapers"
alias g/="cd /"
alias c="clear"
alias mk="mkdir"
alias vim="nvim"
alias v="vim"
alias n="neofetch"
alias ra="ranger"
alias scc="python ~/usr_file/script/SuperClearCR.py"
alias google-chrome-stable='google-chrome-stable --proxy-server="127.0.0.1:45107"'
alias usbl='source ~/usr_file/script/loadusb.sh'
alias usbr='source ~/usr_file/script/removeusb.sh'
alias ds='. $HOME/.config/dashboard-shell/dashboard-shell-run.sh'
alias lg="lazygit"
alias ci="source ~/.config/zsh/conda.zsh"
alias c7="source ~/.config/zsh/py37.zsh"
alias ta="tmux attach"
#alias q="source $HOME/.config/dashboard-shell/add-recent-path.sh && exit"
